"""Create forecasts table

Revision ID: 012071bc4fdc
Revises: 
Create Date: 2025-07-22 14:41:15.320774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012071bc4fdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('predicted_sales', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_dept_id'), ['dept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_store_id'))
        batch_op.drop_index(batch_op.f('ix_forecasts_id'))
        batch_op.drop_index(batch_op.f('ix_forecasts_dept_id'))
        batch_op.drop_index(batch_op.f('ix_forecasts_date'))

    op.drop_table('forecasts')
    # ### end Alembic commands ###
